/**
 * Deterministic Operator Intelligence Fixture Scenarios (OI7).
 * Strictly synthetic read-model fixtures for offline testing, UI validation, and replay demonstration.
 * Invariant: Never present synthetic fixtures as live market evidence.
 */

import type {
  OperatorIntelligenceSnapshot,
  FixtureScenarioId,
} from "@ats/api-client";

// ============================================================================
// 1. NORMAL QUIET MARKET
// ============================================================================
export const SCENARIO_NORMAL_QUIET_MARKET: OperatorIntelligenceSnapshot = {
  provenance: "FIXTURE",
  scenario_id: "NORMAL_QUIET_MARKET",
  scenario_description: "Quiet range-bound session, feeds healthy, zero degradation, normal envelope.",
  survival: {
    effective_survival_state: "NORMAL",
    user_selected_mode: "NORMAL",
    effective_mode: "NORMAL",
    reason_codes: [],
    session_equity: "1000000.00",
    hwm: "1000000.00",
    drawdown_fraction: "0.000",
    available_risk: "50000.00",
    open_positions: 0,
    new_entry_permission: true,
    reduction_permission: true,
    feed_healthy: true,
    broker_healthy: true,
    reconciliation_active: false,
    loss_state: "NORMAL",
    last_state_at: "2026-08-27T09:30:00Z",
  },
  scanner: {
    last_scan_at: "2026-08-27T09:30:00Z",
    data_cutoff: "2026-08-27T09:29:50Z",
    source_state: "FIXTURE",
    funnel: {
      universe_observed: 180,
      fresh: 180,
      stale: 0,
      invalid_reference: 0,
    },
    rejections: {
      liquidity: 45,
      spread: 30,
      calibration: 20,
      negative_ev: 70,
      portfolio_capacity: 0,
      a04: 0,
    },
    candidates_by_class: {
      standard: 15,
      high_conviction: 0,
      convex: 0,
      rare_event: 0,
    },
    candidate_ids: ["cand-nqm-01", "cand-nqm-02"],
  },
  edge_ledger: {
    as_of: "2026-08-27T09:30:00Z",
    source: "FIXTURE",
    entries: [
      {
        candidate_id: "cand-nqm-01",
        timestamp: "2026-08-27T09:30:00Z",
        underlying: "NIFTY",
        instrument: "NIFTY26AUG24500CE",
        direction: "CALL",
        strategy: "MEAN_REVERSION",
        candidate_class: "STANDARD",
        predicted_probability: 0.54,
        market_implied_probability: 0.50,
        gross_edge: 0.45,
        spread_cost: 0.10,
        slippage_estimate: 0.08,
        fees_estimate: 0.04,
        theta_cost: 0.05,
        execution_uncertainty: 0.03,
        calibration_uncertainty: 0.03,
        expected_net_value: 0.12,
        portfolio_penalty: 0.0,
        approved_capital: "25000.00",
        approved_quantity: "50",
        portfolio_brain_outcome: "ALLOW",
        a04_outcome: "ALLOW",
        eventual_outcome: "OPEN",
        realized_pnl: null,
      },
    ],
  },
  agents: [
    {
      agent_id: "session-market-agent",
      role: "Session Market Agent",
      status: "IDLE",
      last_wake: "2026-08-27T09:30:00Z",
      wake_reason: "SCHEDULED_BAR_SYNC",
      data_cutoff: "2026-08-27T09:29:50Z",
      evidence_refs: ["ev-snap-01"],
      recommendation: "MARKET_RANGE_BOUND",
      proposal_id: null,
      authority: "ADVISORY_ONLY",
      latency_ms: 180,
      provider_model: "openrouter/anthropic/claude-3.7-sonnet",
      tool_calls_count: 1,
      is_stale: false,
    },
  ],
  timeline: [
    {
      event_id: "tl-01",
      timestamp: "2026-08-27T09:30:00Z",
      material_event: "SCHEDULED_5M_BAR_CLOSE",
      agent_wake: "Session Market Agent",
      evidence_queried: ["MarketSnapshot"],
      recommendation: "MARKET_RANGE_BOUND",
      proposal_id: null,
      governor_result: "NO_CHANGE",
      authority_note: "ADVISORY_ONLY — deterministic governor authorized",
    },
  ],
  opportunity_map: [
    {
      candidate_id: "cand-nqm-01",
      instrument: "NIFTY26AUG24500CE",
      underlying: "NIFTY",
      candidate_class: "STANDARD",
      calibrated_probability: 0.54,
      expected_net_value: 0.12,
      asymmetry: 1.4,
      liquidity_score: 85,
      spread_ticks: 2,
      analogue_support: 0.65,
      portfolio_brain_outcome: "ALLOW",
      a04_outcome: "ALLOW",
    },
  ],
  evidence_lineage: {
    "cand-nqm-01": [
      {
        node_type: "MarketSnapshot",
        node_id: "n-01",
        timestamp: "2026-08-27T09:30:00Z",
        status: "VERIFIED",
        metrics: { spot: 24500.0, spread: 2 },
        hash: "a1b2c3d4e5f601",
        summary: "Quiet market snapshot verified.",
      },
    ],
  },
};

// ============================================================================
// 2. HIGH CONVICTION CANDIDATE
// ============================================================================
export const SCENARIO_HIGH_CONVICTION_CANDIDATE: OperatorIntelligenceSnapshot = {
  provenance: "FIXTURE",
  scenario_id: "HIGH_CONVICTION_CANDIDATE",
  scenario_description: "NIFTY Bull Call Spread with 0.78 probability and strong net edge.",
  survival: {
    effective_survival_state: "NORMAL",
    user_selected_mode: "NORMAL",
    effective_mode: "NORMAL",
    reason_codes: [],
    session_equity: "1005000.00",
    hwm: "1005000.00",
    drawdown_fraction: "0.000",
    available_risk: "45000.00",
    open_positions: 0,
    new_entry_permission: true,
    reduction_permission: true,
    feed_healthy: true,
    broker_healthy: true,
    reconciliation_active: false,
    loss_state: "NORMAL",
    last_state_at: "2026-08-27T10:15:00Z",
  },
  scanner: {
    last_scan_at: "2026-08-27T10:15:00Z",
    data_cutoff: "2026-08-27T10:14:50Z",
    source_state: "FIXTURE",
    funnel: { universe_observed: 180, fresh: 180, stale: 0, invalid_reference: 0 },
    rejections: { liquidity: 40, spread: 25, calibration: 15, negative_ev: 50, portfolio_capacity: 0, a04: 0 },
    candidates_by_class: { standard: 20, high_conviction: 3, convex: 0, rare_event: 0 },
    candidate_ids: ["cand-hc-99"],
  },
  edge_ledger: {
    as_of: "2026-08-27T10:15:00Z",
    source: "FIXTURE",
    entries: [
      {
        candidate_id: "cand-hc-99",
        timestamp: "2026-08-27T10:15:00Z",
        underlying: "NIFTY",
        instrument: "NIFTY26AUG24600CE_SPREAD",
        direction: "CALL",
        strategy: "VOL_EXPANSION",
        candidate_class: "HIGH_CONVICTION",
        predicted_probability: 0.78,
        market_implied_probability: 0.52,
        gross_edge: 2.10,
        spread_cost: 0.15,
        slippage_estimate: 0.10,
        fees_estimate: 0.05,
        theta_cost: 0.10,
        execution_uncertainty: 0.05,
        calibration_uncertainty: 0.05,
        expected_net_value: 1.60,
        portfolio_penalty: 0.0,
        approved_capital: "50000.00",
        approved_quantity: "75",
        portfolio_brain_outcome: "ALLOW",
        a04_outcome: "ALLOW",
        eventual_outcome: "WIN",
        realized_pnl: "+1.55R",
      },
    ],
  },
  agents: [
    {
      agent_id: "session-market-agent",
      role: "Session Market Agent",
      status: "ACTIVE",
      last_wake: "2026-08-27T10:15:00Z",
      wake_reason: "VOLATILITY_EXPANSION_TRIGGER",
      data_cutoff: "2026-08-27T10:14:50Z",
      evidence_refs: ["ev-snap-hc-01", "ev-regime-hc-02"],
      recommendation: "VOL_EXPANSION_BULL_CALL",
      proposal_id: "prop-hc-01",
      authority: "ADVISORY_ONLY",
      latency_ms: 240,
      provider_model: "openrouter/anthropic/claude-3.7-sonnet",
      tool_calls_count: 3,
      is_stale: false,
    },
  ],
  timeline: [
    {
      event_id: "tl-hc-01",
      timestamp: "2026-08-27T10:15:00Z",
      material_event: "NIFTY BREAKOUT & IV SURGE",
      agent_wake: "Session Market Agent",
      evidence_queried: ["RegimeEvidence", "EnsembleForecast"],
      recommendation: "VOL_EXPANSION_BULL_CALL",
      proposal_id: "prop-hc-01",
      governor_result: "APPROVED",
      authority_note: "ADVISORY_ONLY — deterministic governor authorized",
    },
  ],
  opportunity_map: [
    {
      candidate_id: "cand-hc-99",
      instrument: "NIFTY26AUG24600CE_SPREAD",
      underlying: "NIFTY",
      candidate_class: "HIGH_CONVICTION",
      calibrated_probability: 0.78,
      expected_net_value: 1.60,
      asymmetry: 3.2,
      liquidity_score: 90,
      spread_ticks: 3,
      analogue_support: 0.88,
      portfolio_brain_outcome: "ALLOW",
      a04_outcome: "ALLOW",
    },
  ],
  evidence_lineage: {
    "cand-hc-99": [
      {
        node_type: "MarketSnapshot",
        node_id: "n-hc-01",
        timestamp: "2026-08-27T10:14:50Z",
        status: "VERIFIED",
        metrics: { spot: 24580.0, iv_atm: 15.2 },
        hash: "hc-snap-hash-01",
        summary: "Breakout volume and IV surge detected.",
      },
      {
        node_type: "OpportunityCandidate",
        node_id: "n-hc-02",
        timestamp: "2026-08-27T10:15:00Z",
        status: "VERIFIED",
        metrics: { prob: 0.78, net_ev: 1.60 },
        hash: "hc-cand-hash-02",
        summary: "Candidate classified as HIGH_CONVICTION.",
      },
    ],
  },
};

// ============================================================================
// 3. HYPOTHETICAL CONVEX CANDIDATE
// ============================================================================
export const SCENARIO_HYPOTHETICAL_CONVEX_CANDIDATE: OperatorIntelligenceSnapshot = {
  provenance: "FIXTURE",
  scenario_id: "HYPOTHETICAL_CONVEX_CANDIDATE",
  scenario_description: "Asymmetric out-of-the-money option with 0.35 probability and 8.5x payoff asymmetry.",
  survival: {
    effective_survival_state: "NORMAL",
    user_selected_mode: "NORMAL",
    effective_mode: "NORMAL",
    reason_codes: [],
    session_equity: "1000000.00",
    hwm: "1000000.00",
    drawdown_fraction: "0.000",
    available_risk: "50000.00",
    open_positions: 0,
    new_entry_permission: true,
    reduction_permission: true,
    feed_healthy: true,
    broker_healthy: true,
    reconciliation_active: false,
    loss_state: "NORMAL",
    last_state_at: "2026-08-27T11:00:00Z",
  },
  scanner: {
    last_scan_at: "2026-08-27T11:00:00Z",
    data_cutoff: "2026-08-27T10:59:50Z",
    source_state: "FIXTURE",
    funnel: { universe_observed: 180, fresh: 180, stale: 0, invalid_reference: 0 },
    rejections: { liquidity: 50, spread: 30, calibration: 20, negative_ev: 60, portfolio_capacity: 0, a04: 0 },
    candidates_by_class: { standard: 10, high_conviction: 1, convex: 2, rare_event: 0 },
    candidate_ids: ["cand-cx-01"],
  },
  edge_ledger: {
    as_of: "2026-08-27T11:00:00Z",
    source: "FIXTURE",
    entries: [
      {
        candidate_id: "cand-cx-01",
        timestamp: "2026-08-27T11:00:00Z",
        underlying: "BANKNIFTY",
        instrument: "BANKNIFTY26AUG53000CE",
        direction: "CALL",
        strategy: "CONVEXITY_SURGE",
        candidate_class: "CONVEX",
        predicted_probability: 0.35,
        market_implied_probability: 0.18,
        gross_edge: 3.50,
        spread_cost: 0.20,
        slippage_estimate: 0.15,
        fees_estimate: 0.05,
        theta_cost: 0.30,
        execution_uncertainty: 0.10,
        calibration_uncertainty: 0.10,
        expected_net_value: 2.60,
        portfolio_penalty: 0.20,
        approved_capital: "15000.00",
        approved_quantity: "30",
        portfolio_brain_outcome: "ALLOW_REDUCED",
        a04_outcome: "ALLOW",
        eventual_outcome: "OPEN",
        realized_pnl: null,
      },
    ],
  },
  agents: [
    {
      agent_id: "research-agent",
      role: "Research Agent",
      status: "ACTIVE",
      last_wake: "2026-08-27T11:00:00Z",
      wake_reason: "CONVEXITY_SCAN",
      data_cutoff: "2026-08-27T10:59:50Z",
      evidence_refs: ["ev-cx-01"],
      recommendation: "CONVEX_TAIL_ALLOCATION",
      proposal_id: "prop-cx-01",
      authority: "ADVISORY_ONLY",
      latency_ms: 310,
      provider_model: "openrouter/anthropic/claude-3.7-sonnet",
      tool_calls_count: 2,
      is_stale: false,
    },
  ],
  timeline: [
    {
      event_id: "tl-cx-01",
      timestamp: "2026-08-27T11:00:00Z",
      material_event: "BANKNIFTY SKEW DISLOCATION",
      agent_wake: "Research Agent",
      evidence_queried: ["ConvexityEvidence"],
      recommendation: "CONVEX_TAIL_ALLOCATION",
      proposal_id: "prop-cx-01",
      governor_result: "APPROVED",
      authority_note: "ADVISORY_ONLY — deterministic governor authorized",
    },
  ],
  opportunity_map: [
    {
      candidate_id: "cand-cx-01",
      instrument: "BANKNIFTY26AUG53000CE",
      underlying: "BANKNIFTY",
      candidate_class: "CONVEX",
      calibrated_probability: 0.35,
      expected_net_value: 2.60,
      asymmetry: 8.5,
      liquidity_score: 65,
      spread_ticks: 5,
      analogue_support: 0.55,
      portfolio_brain_outcome: "ALLOW_REDUCED",
      a04_outcome: "ALLOW",
    },
  ],
  evidence_lineage: {
    "cand-cx-01": [
      {
        node_type: "ConvexityEvidence",
        node_id: "n-cx-01",
        timestamp: "2026-08-27T11:00:00Z",
        status: "VERIFIED",
        metrics: { asymmetry: 8.5, tail_risk_ratio: 4.2 },
        hash: "cx-node-hash-01",
        summary: "Extreme convexity pricing verified against historical analogues.",
      },
    ],
  },
};

// ============================================================================
// 4. HYPOTHETICAL RARE EVENT CANDIDATE
// ============================================================================
export const SCENARIO_HYPOTHETICAL_RARE_EVENT_CANDIDATE: OperatorIntelligenceSnapshot = {
  provenance: "FIXTURE",
  scenario_id: "HYPOTHETICAL_RARE_EVENT_CANDIDATE",
  scenario_description: "Structural gap/tail event trigger evaluated under high uncertainty.",
  survival: {
    effective_survival_state: "CAUTION",
    user_selected_mode: "NORMAL",
    effective_mode: "NORMAL",
    reason_codes: ["VOLATILITY_SPIKE"],
    session_equity: "998000.00",
    hwm: "1000000.00",
    drawdown_fraction: "0.002",
    available_risk: "30000.00",
    open_positions: 0,
    new_entry_permission: true,
    reduction_permission: true,
    feed_healthy: true,
    broker_healthy: true,
    reconciliation_active: false,
    loss_state: "CAUTION",
    last_state_at: "2026-08-27T11:30:00Z",
  },
  scanner: {
    last_scan_at: "2026-08-27T11:30:00Z",
    data_cutoff: "2026-08-27T11:29:50Z",
    source_state: "FIXTURE",
    funnel: { universe_observed: 180, fresh: 175, stale: 5, invalid_reference: 0 },
    rejections: { liquidity: 60, spread: 40, calibration: 30, negative_ev: 40, portfolio_capacity: 0, a04: 0 },
    candidates_by_class: { standard: 5, high_conviction: 0, convex: 1, rare_event: 1 },
    candidate_ids: ["cand-re-01"],
  },
  edge_ledger: {
    as_of: "2026-08-27T11:30:00Z",
    source: "FIXTURE",
    entries: [
      {
        candidate_id: "cand-re-01",
        timestamp: "2026-08-27T11:30:00Z",
        underlying: "NIFTY",
        instrument: "NIFTY26AUG24000PE",
        direction: "PUT",
        strategy: "TAIL_RISK_HEDGE",
        candidate_class: "RARE_EVENT",
        predicted_probability: 0.22,
        market_implied_probability: 0.08,
        gross_edge: 4.80,
        spread_cost: 0.30,
        slippage_estimate: 0.25,
        fees_estimate: 0.05,
        theta_cost: 0.40,
        execution_uncertainty: 0.30,
        calibration_uncertainty: 0.30,
        expected_net_value: 3.20,
        portfolio_penalty: 0.50,
        approved_capital: "10000.00",
        approved_quantity: "25",
        portfolio_brain_outcome: "ALLOW_REDUCED",
        a04_outcome: "ALLOW",
        eventual_outcome: "OPEN",
        realized_pnl: null,
      },
    ],
  },
  agents: [
    {
      agent_id: "session-market-agent",
      role: "Session Market Agent",
      status: "ACTIVE",
      last_wake: "2026-08-27T11:30:00Z",
      wake_reason: "TAIL_DISLOCATION_DETECTED",
      data_cutoff: "2026-08-27T11:29:50Z",
      evidence_refs: ["ev-re-01"],
      recommendation: "TAIL_RISK_HEDGE_PROPOSAL",
      proposal_id: "prop-re-01",
      authority: "ADVISORY_ONLY",
      latency_ms: 420,
      provider_model: "openrouter/anthropic/claude-3.7-sonnet",
      tool_calls_count: 5,
      is_stale: false,
    },
  ],
  timeline: [
    {
      event_id: "tl-re-01",
      timestamp: "2026-08-27T11:30:00Z",
      material_event: "FLASH SKEW DIVERGENCE",
      agent_wake: "Session Market Agent",
      evidence_queried: ["RegimeEvidence", "HistoricalAnalogueEvidence"],
      recommendation: "TAIL_RISK_HEDGE_PROPOSAL",
      proposal_id: "prop-re-01",
      governor_result: "APPROVED",
      authority_note: "ADVISORY_ONLY — deterministic governor authorized",
    },
  ],
  opportunity_map: [
    {
      candidate_id: "cand-re-01",
      instrument: "NIFTY26AUG24000PE",
      underlying: "NIFTY",
      candidate_class: "RARE_EVENT",
      calibrated_probability: 0.22,
      expected_net_value: 3.20,
      asymmetry: 12.0,
      liquidity_score: 50,
      spread_ticks: 8,
      analogue_support: 0.40,
      portfolio_brain_outcome: "ALLOW_REDUCED",
      a04_outcome: "ALLOW",
    },
  ],
  evidence_lineage: {
    "cand-re-01": [
      {
        node_type: "RegimeEvidence",
        node_id: "n-re-01",
        timestamp: "2026-08-27T11:30:00Z",
        status: "VERIFIED",
        metrics: { tail_sigma: 3.8 },
        hash: "re-node-hash-01",
        summary: "3.8-sigma tail event anomaly detected.",
      },
    ],
  },
};

// ============================================================================
// 5. SAFE DUE DRAWDOWN
// ============================================================================
export const SCENARIO_SAFE_DUE_DRAWDOWN: OperatorIntelligenceSnapshot = {
  provenance: "FIXTURE",
  scenario_id: "SAFE_DUE_DRAWDOWN",
  scenario_description: "Session drawdown of -1.8% triggers auto de-escalation to SAFE mode.",
  survival: {
    effective_survival_state: "SAFE",
    user_selected_mode: "NORMAL",
    effective_mode: "SAFE",
    reason_codes: ["SESSION_DRAWDOWN", "CAPITAL_PROTECTION_ENVELOPE"],
    session_equity: "982000.00",
    hwm: "1000000.00",
    drawdown_fraction: "0.018",
    available_risk: "20000.00",
    open_positions: 1,
    new_entry_permission: false,
    reduction_permission: true,
    feed_healthy: true,
    broker_healthy: true,
    reconciliation_active: false,
    loss_state: "CAUTION",
    last_state_at: "2026-08-27T12:00:00Z",
  },
  scanner: {
    last_scan_at: "2026-08-27T12:00:00Z",
    data_cutoff: "2026-08-27T11:59:50Z",
    source_state: "FIXTURE",
    funnel: { universe_observed: 180, fresh: 180, stale: 0, invalid_reference: 0 },
    rejections: { liquidity: 30, spread: 20, calibration: 10, negative_ev: 80, portfolio_capacity: 35, a04: 5 },
    candidates_by_class: { standard: 0, high_conviction: 0, convex: 0, rare_event: 0 },
    candidate_ids: [],
  },
  edge_ledger: {
    as_of: "2026-08-27T12:00:00Z",
    source: "FIXTURE",
    entries: [],
  },
  agents: [
    {
      agent_id: "position-agent",
      role: "Position Agent",
      status: "ACTIVE",
      last_wake: "2026-08-27T12:00:00Z",
      wake_reason: "DRAWDOWN_THRESHOLD_ALERT",
      data_cutoff: "2026-08-27T11:59:50Z",
      evidence_refs: ["ev-dd-01"],
      recommendation: "ENFORCE_SAFE_ENVELOPE",
      proposal_id: "prop-safe-01",
      authority: "ADVISORY_ONLY",
      latency_ms: 190,
      provider_model: "openrouter/anthropic/claude-3.7-sonnet",
      tool_calls_count: 1,
      is_stale: false,
    },
  ],
  timeline: [
    {
      event_id: "tl-dd-01",
      timestamp: "2026-08-27T12:00:00Z",
      material_event: "SESSION DRAWDOWN EXCEEDS 1.5%",
      agent_wake: "Position Agent",
      evidence_queried: ["RiskFacts"],
      recommendation: "ENFORCE_SAFE_ENVELOPE",
      proposal_id: "prop-safe-01",
      governor_result: "APPROVED",
      authority_note: "ADVISORY_ONLY — deterministic governor authorized",
    },
  ],
  opportunity_map: [],
  evidence_lineage: {},
};

// ============================================================================
// 6. SYSTEM HALTED
// ============================================================================
export const SCENARIO_HALTED: OperatorIntelligenceSnapshot = {
  provenance: "FIXTURE",
  scenario_id: "HALTED",
  scenario_description: "Circuit breaker / emergency halt active, all new entries prohibited.",
  survival: {
    effective_survival_state: "HALTED",
    user_selected_mode: "NORMAL",
    effective_mode: "HALTED",
    reason_codes: ["SAFETY_HALTED", "CIRCUIT_BREAKER_TRIGGERED"],
    session_equity: "970000.00",
    hwm: "1000000.00",
    drawdown_fraction: "0.030",
    available_risk: "0.00",
    open_positions: 0,
    new_entry_permission: false,
    reduction_permission: true,
    feed_healthy: true,
    broker_healthy: true,
    reconciliation_active: false,
    loss_state: "HALTED",
    last_state_at: "2026-08-27T12:30:00Z",
  },
  scanner: {
    last_scan_at: "2026-08-27T12:30:00Z",
    data_cutoff: "2026-08-27T12:29:50Z",
    source_state: "FIXTURE",
    funnel: { universe_observed: 180, fresh: 180, stale: 0, invalid_reference: 0 },
    rejections: { liquidity: 0, spread: 0, calibration: 0, negative_ev: 0, portfolio_capacity: 0, a04: 180 },
    candidates_by_class: { standard: 0, high_conviction: 0, convex: 0, rare_event: 0 },
    candidate_ids: [],
  },
  edge_ledger: { as_of: "2026-08-27T12:30:00Z", source: "FIXTURE", entries: [] },
  agents: [
    {
      agent_id: "portfolio-analyst-agent",
      role: "Portfolio Analyst Agent",
      status: "DEGRADED",
      last_wake: "2026-08-27T12:30:00Z",
      wake_reason: "SAFETY_HALT_BROADCAST",
      data_cutoff: "2026-08-27T12:29:50Z",
      evidence_refs: [],
      recommendation: "HALT_COMPLIANCE_CONFIRMED",
      proposal_id: null,
      authority: "ADVISORY_ONLY",
      latency_ms: 120,
      provider_model: "openrouter/anthropic/claude-3.7-sonnet",
      tool_calls_count: 0,
      is_stale: false,
    },
  ],
  timeline: [
    {
      event_id: "tl-halt-01",
      timestamp: "2026-08-27T12:30:00Z",
      material_event: "OPERATOR_EMERGENCY_HALT",
      agent_wake: "Portfolio Analyst Agent",
      evidence_queried: [],
      recommendation: "HALT_COMPLIANCE_CONFIRMED",
      proposal_id: null,
      governor_result: "APPROVED",
      authority_note: "ADVISORY_ONLY — deterministic governor authorized",
    },
  ],
  opportunity_map: [],
  evidence_lineage: {},
};

// ============================================================================
// 7. HARNESS UNAVAILABLE
// ============================================================================
export const SCENARIO_HARNESS_UNAVAILABLE: OperatorIntelligenceSnapshot = {
  provenance: "FIXTURE",
  scenario_id: "HARNESS_UNAVAILABLE",
  scenario_description: "Intelligence harness offline; deterministic defensive fallback active.",
  survival: {
    effective_survival_state: "SAFE",
    user_selected_mode: "NORMAL",
    effective_mode: "SAFE",
    reason_codes: ["HARNESS_OFFLINE", "DEFENSIVE_FALLBACK"],
    session_equity: "1000000.00",
    hwm: "1000000.00",
    drawdown_fraction: "0.000",
    available_risk: "15000.00",
    open_positions: 0,
    new_entry_permission: false,
    reduction_permission: true,
    feed_healthy: true,
    broker_healthy: true,
    reconciliation_active: false,
    loss_state: "CAUTION",
    last_state_at: "2026-08-27T13:00:00Z",
  },
  scanner: {
    last_scan_at: "2026-08-27T13:00:00Z",
    data_cutoff: "2026-08-27T12:59:50Z",
    source_state: "STALE",
    funnel: { universe_observed: 180, fresh: 0, stale: 180, invalid_reference: 0 },
    rejections: { liquidity: 0, spread: 0, calibration: 0, negative_ev: 0, portfolio_capacity: 0, a04: 0 },
    candidates_by_class: { standard: 0, high_conviction: 0, convex: 0, rare_event: 0 },
    candidate_ids: [],
  },
  edge_ledger: { as_of: "2026-08-27T13:00:00Z", source: "FIXTURE", entries: [] },
  agents: [
    {
      agent_id: "session-market-agent",
      role: "Session Market Agent",
      status: "OFFLINE",
      last_wake: null,
      wake_reason: null,
      data_cutoff: null,
      evidence_refs: [],
      recommendation: null,
      proposal_id: null,
      authority: "ADVISORY_ONLY",
      latency_ms: null,
      provider_model: null,
      tool_calls_count: 0,
      is_stale: true,
    },
    {
      agent_id: "position-agent",
      role: "Position Agent",
      status: "OFFLINE",
      last_wake: null,
      wake_reason: null,
      data_cutoff: null,
      evidence_refs: [],
      recommendation: null,
      proposal_id: null,
      authority: "ADVISORY_ONLY",
      latency_ms: null,
      provider_model: null,
      tool_calls_count: 0,
      is_stale: true,
    },
  ],
  timeline: [],
  opportunity_map: [],
  evidence_lineage: {},
};

// ============================================================================
// 8. STALE AGENT ADVISORY
// ============================================================================
export const SCENARIO_STALE_AGENT_ADVISORY: OperatorIntelligenceSnapshot = {
  provenance: "FIXTURE",
  scenario_id: "STALE_AGENT_ADVISORY",
  scenario_description: "Session Market Agent wake time exceeds TTL; advisory marked STALE.",
  survival: {
    effective_survival_state: "CAUTION",
    user_selected_mode: "NORMAL",
    effective_mode: "NORMAL",
    reason_codes: ["AGENT_ADVISORY_STALE"],
    session_equity: "1002000.00",
    hwm: "1002000.00",
    drawdown_fraction: "0.000",
    available_risk: "40000.00",
    open_positions: 0,
    new_entry_permission: true,
    reduction_permission: true,
    feed_healthy: true,
    broker_healthy: true,
    reconciliation_active: false,
    loss_state: "CAUTION",
    last_state_at: "2026-08-27T13:30:00Z",
  },
  scanner: {
    last_scan_at: "2026-08-27T13:30:00Z",
    data_cutoff: "2026-08-27T13:29:50Z",
    source_state: "FIXTURE",
    funnel: { universe_observed: 180, fresh: 170, stale: 10, invalid_reference: 0 },
    rejections: { liquidity: 30, spread: 20, calibration: 20, negative_ev: 90, portfolio_capacity: 0, a04: 0 },
    candidates_by_class: { standard: 12, high_conviction: 0, convex: 0, rare_event: 0 },
    candidate_ids: ["cand-stale-01"],
  },
  edge_ledger: {
    as_of: "2026-08-27T13:30:00Z",
    source: "FIXTURE",
    entries: [
      {
        candidate_id: "cand-stale-01",
        timestamp: "2026-08-27T13:10:00Z",
        underlying: "NIFTY",
        instrument: "NIFTY26AUG24600PE",
        direction: "PUT",
        strategy: "MEAN_REVERSION",
        candidate_class: "STANDARD",
        predicted_probability: 0.55,
        market_implied_probability: 0.49,
        gross_edge: 0.50,
        spread_cost: 0.15,
        slippage_estimate: 0.10,
        fees_estimate: 0.05,
        theta_cost: 0.10,
        execution_uncertainty: 0.05,
        calibration_uncertainty: 0.05,
        expected_net_value: 0.05,
        portfolio_penalty: 0.0,
        approved_capital: "20000.00",
        approved_quantity: "50",
        portfolio_brain_outcome: "ALLOW",
        a04_outcome: "ALLOW",
        eventual_outcome: null,
        realized_pnl: null,
      },
    ],
  },
  agents: [
    {
      agent_id: "session-market-agent",
      role: "Session Market Agent",
      status: "STALE",
      last_wake: "2026-08-27T13:10:00Z",
      wake_reason: "PREVIOUS_CYCLE",
      data_cutoff: "2026-08-27T13:09:00Z",
      evidence_refs: ["ev-stale-01"],
      recommendation: "VOL_EXPANSION_LAGGING",
      proposal_id: "prop-stale-01",
      authority: "ADVISORY_ONLY",
      latency_ms: 1200,
      provider_model: "openrouter/anthropic/claude-3.7-sonnet",
      tool_calls_count: 2,
      is_stale: true,
    },
  ],
  timeline: [],
  opportunity_map: [
    {
      candidate_id: "cand-stale-01",
      instrument: "NIFTY26AUG24600PE",
      underlying: "NIFTY",
      candidate_class: "STANDARD",
      calibrated_probability: 0.55,
      expected_net_value: 0.05,
      asymmetry: 1.2,
      liquidity_score: 75,
      spread_ticks: 3,
      analogue_support: null,
      portfolio_brain_outcome: "ALLOW",
      a04_outcome: "ALLOW",
    },
  ],
  evidence_lineage: {},
};

// ============================================================================
// 9. CANDIDATE REJECTED BY PORTFOLIO BRAIN
// ============================================================================
export const SCENARIO_CANDIDATE_REJECTED_PORTFOLIO_BRAIN: OperatorIntelligenceSnapshot = {
  provenance: "FIXTURE",
  scenario_id: "CANDIDATE_REJECTED_PORTFOLIO_BRAIN",
  scenario_description: "Positive Net EV candidate rejected by Portfolio Brain due to sector concentration limit.",
  survival: {
    effective_survival_state: "NORMAL",
    user_selected_mode: "NORMAL",
    effective_mode: "NORMAL",
    reason_codes: [],
    session_equity: "1000000.00",
    hwm: "1000000.00",
    drawdown_fraction: "0.000",
    available_risk: "10000.00",
    open_positions: 2,
    new_entry_permission: true,
    reduction_permission: true,
    feed_healthy: true,
    broker_healthy: true,
    reconciliation_active: false,
    loss_state: "NORMAL",
    last_state_at: "2026-08-27T14:00:00Z",
  },
  scanner: {
    last_scan_at: "2026-08-27T14:00:00Z",
    data_cutoff: "2026-08-27T13:59:50Z",
    source_state: "FIXTURE",
    funnel: { universe_observed: 180, fresh: 180, stale: 0, invalid_reference: 0 },
    rejections: { liquidity: 20, spread: 15, calibration: 10, negative_ev: 30, portfolio_capacity: 45, a04: 0 },
    candidates_by_class: { standard: 10, high_conviction: 2, convex: 0, rare_event: 0 },
    candidate_ids: ["cand-rej-pb-01"],
  },
  edge_ledger: {
    as_of: "2026-08-27T14:00:00Z",
    source: "FIXTURE",
    entries: [
      {
        candidate_id: "cand-rej-pb-01",
        timestamp: "2026-08-27T14:00:00Z",
        underlying: "BANKNIFTY",
        instrument: "BANKNIFTY26AUG52000CE",
        direction: "CALL",
        strategy: "BREAKOUT",
        candidate_class: "HIGH_CONVICTION",
        predicted_probability: 0.72,
        market_implied_probability: 0.48,
        gross_edge: 1.60,
        spread_cost: 0.15,
        slippage_estimate: 0.10,
        fees_estimate: 0.05,
        theta_cost: 0.10,
        execution_uncertainty: 0.05,
        calibration_uncertainty: 0.05,
        expected_net_value: 1.10,
        portfolio_penalty: 1.50,
        approved_capital: "0.00",
        approved_quantity: "0",
        portfolio_brain_outcome: "DENY",
        a04_outcome: "DENY",
        eventual_outcome: null,
        realized_pnl: null,
      },
    ],
  },
  agents: [],
  timeline: [],
  opportunity_map: [
    {
      candidate_id: "cand-rej-pb-01",
      instrument: "BANKNIFTY26AUG52000CE",
      underlying: "BANKNIFTY",
      candidate_class: "HIGH_CONVICTION",
      calibrated_probability: 0.72,
      expected_net_value: 1.10,
      asymmetry: 2.8,
      liquidity_score: 80,
      spread_ticks: 4,
      analogue_support: 0.75,
      portfolio_brain_outcome: "DENY",
      a04_outcome: "DENY",
    },
  ],
  evidence_lineage: {
    "cand-rej-pb-01": [
      {
        node_type: "PortfolioAllocationDecision",
        node_id: "n-pb-rej-01",
        timestamp: "2026-08-27T14:00:00Z",
        status: "REJECTED",
        metrics: { capacity_limit: 50000, current_exposure: 50000, penalty: 1.5 },
        hash: "pb-rej-hash-01",
        summary: "Portfolio Brain DENY: Sector capacity for BANKNIFTY fully utilized.",
      },
    ],
  },
};

// ============================================================================
// 10. CANDIDATE DENIED BY A04
// ============================================================================
export const SCENARIO_CANDIDATE_DENIED_A04: OperatorIntelligenceSnapshot = {
  provenance: "FIXTURE",
  scenario_id: "CANDIDATE_DENIED_A04",
  scenario_description: "Candidate denied by deterministic A04 kernel due to spread tolerance exceeded.",
  survival: {
    effective_survival_state: "NORMAL",
    user_selected_mode: "NORMAL",
    effective_mode: "NORMAL",
    reason_codes: [],
    session_equity: "1000000.00",
    hwm: "1000000.00",
    drawdown_fraction: "0.000",
    available_risk: "40000.00",
    open_positions: 0,
    new_entry_permission: true,
    reduction_permission: true,
    feed_healthy: true,
    broker_healthy: true,
    reconciliation_active: false,
    loss_state: "NORMAL",
    last_state_at: "2026-08-27T14:30:00Z",
  },
  scanner: {
    last_scan_at: "2026-08-27T14:30:00Z",
    data_cutoff: "2026-08-27T14:29:50Z",
    source_state: "FIXTURE",
    funnel: { universe_observed: 180, fresh: 180, stale: 0, invalid_reference: 0 },
    rejections: { liquidity: 10, spread: 20, calibration: 10, negative_ev: 40, portfolio_capacity: 0, a04: 12 },
    candidates_by_class: { standard: 5, high_conviction: 0, convex: 0, rare_event: 0 },
    candidate_ids: ["cand-rej-a04-01"],
  },
  edge_ledger: {
    as_of: "2026-08-27T14:30:00Z",
    source: "FIXTURE",
    entries: [
      {
        candidate_id: "cand-rej-a04-01",
        timestamp: "2026-08-27T14:30:00Z",
        underlying: "NIFTY",
        instrument: "NIFTY26AUG24800CE",
        direction: "CALL",
        strategy: "MOMENTUM",
        candidate_class: "STANDARD",
        predicted_probability: 0.60,
        market_implied_probability: 0.45,
        gross_edge: 0.80,
        spread_cost: 0.45,
        slippage_estimate: 0.20,
        fees_estimate: 0.05,
        theta_cost: 0.10,
        execution_uncertainty: 0.10,
        calibration_uncertainty: 0.10,
        expected_net_value: -0.20,
        portfolio_penalty: 0.0,
        approved_capital: "0.00",
        approved_quantity: "0",
        portfolio_brain_outcome: "DEFER",
        a04_outcome: "DENY",
        eventual_outcome: null,
        realized_pnl: null,
      },
    ],
  },
  agents: [],
  timeline: [],
  opportunity_map: [
    {
      candidate_id: "cand-rej-a04-01",
      instrument: "NIFTY26AUG24800CE",
      underlying: "NIFTY",
      candidate_class: "STANDARD",
      calibrated_probability: 0.60,
      expected_net_value: -0.20,
      asymmetry: 1.5,
      liquidity_score: 40,
      spread_ticks: 9,
      analogue_support: null,
      portfolio_brain_outcome: "DEFER",
      a04_outcome: "DENY",
    },
  ],
  evidence_lineage: {
    "cand-rej-a04-01": [
      {
        node_type: "A04Decision",
        node_id: "n-a04-rej-01",
        timestamp: "2026-08-27T14:30:00Z",
        status: "REJECTED",
        metrics: { spread_ticks: 9, max_spread_ticks: 6, kernel_decision: "DENY" },
        hash: "a04-rej-hash-01",
        summary: "A04 Kernel DENY: Spread 9 ticks exceeds tolerance limit of 6 ticks.",
      },
    ],
  },
};

// ============================================================================
// ALL 10 SCENARIOS MAP
// ============================================================================
export const FIXTURE_SCENARIOS: Record<FixtureScenarioId, OperatorIntelligenceSnapshot> = {
  NORMAL_QUIET_MARKET: SCENARIO_NORMAL_QUIET_MARKET,
  HIGH_CONVICTION_CANDIDATE: SCENARIO_HIGH_CONVICTION_CANDIDATE,
  HYPOTHETICAL_CONVEX_CANDIDATE: SCENARIO_HYPOTHETICAL_CONVEX_CANDIDATE,
  HYPOTHETICAL_RARE_EVENT_CANDIDATE: SCENARIO_HYPOTHETICAL_RARE_EVENT_CANDIDATE,
  SAFE_DUE_DRAWDOWN: SCENARIO_SAFE_DUE_DRAWDOWN,
  HALTED: SCENARIO_HALTED,
  HARNESS_UNAVAILABLE: SCENARIO_HARNESS_UNAVAILABLE,
  STALE_AGENT_ADVISORY: SCENARIO_STALE_AGENT_ADVISORY,
  CANDIDATE_REJECTED_PORTFOLIO_BRAIN: SCENARIO_CANDIDATE_REJECTED_PORTFOLIO_BRAIN,
  CANDIDATE_DENIED_A04: SCENARIO_CANDIDATE_DENIED_A04,
};

export function getFixtureScenario(id: FixtureScenarioId): OperatorIntelligenceSnapshot {
  return FIXTURE_SCENARIOS[id] ?? SCENARIO_NORMAL_QUIET_MARKET;
}
