"use client";

import { useMemo } from "react";
import { useOperatorState } from "../system/OperatorStateProvider";
import { MetricStrip } from "../system/MetricStrip";
import { EmptyState, LoadingState, Panel } from "../system/SurfaceStates";
import { StatusBadge } from "../system/SystemHealthIndicator";

const amount = (value: string | undefined) => value === undefined ? "—" : `₹${Number(value).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
export function PortfolioRiskView({ focus = "risk" }: { focus?: "risk" | "portfolio" }) {
  const { runtime, loading } = useOperatorState();
  const exposures = useMemo(() => { const map = new Map<string, number>(); for (const position of runtime?.open_positions ?? []) { const underlying = position.instrument_id.toUpperCase().includes("BANKNIFTY") ? "BANKNIFTY" : position.instrument_id.toUpperCase().includes("NIFTY") ? "NIFTY" : "OTHER"; map.set(underlying, (map.get(underlying) ?? 0) + Math.abs(Number(position.quantity) * Number(position.mark_price ?? position.entry_price))); } return [...map.entries()].sort((a, b) => b[1] - a[1]); }, [runtime?.open_positions]);
  const drawdown = Number(runtime?.pnl.drawdown_fraction ?? 0);
  return <div className="ats-page"><div className="ats-page-heading"><div><span className="eyebrow">PORTFOLIO AUTHORITY</span><h1>{focus === "portfolio" ? "Portfolio" : "Risk"}</h1><p>Capital, exposure, drawdown, and deterministic decision evidence without frontend authority.</p></div><StatusBadge state={runtime?.loss_state === "NORMAL" ? "HEALTHY" : runtime?.loss_state === "HALTED" ? "HALTED" : runtime ? "DEGRADED" : "UNKNOWN"}>{runtime?.loss_state ?? "LOSS STATE"}</StatusBadge></div>
    <MetricStrip ariaLabel="Capital allocation" items={[{ label: "Total", value: amount(runtime?.capital.total) }, { label: "Deployable", value: amount(runtime?.capital.available) }, { label: "Available", value: amount(runtime?.capital.available) }, { label: "Reserved", value: amount(runtime?.capital.reserved) }, { label: "Inflight", value: amount(runtime?.capital.inflight) }, { label: "Committed", value: amount(runtime?.capital.used) }]} />
    <div className="risk-grid"><Panel title="Exposure by underlying" eyebrow="CURRENT PAPER NOTIONAL" className="risk-exposure">{loading && !runtime ? <LoadingState rows={4} /> : exposures.length ? <div className="exposure-bars">{exposures.map(([name, value]) => <div key={name}><span>{name}</span><i><b style={{ width: `${Math.min(100, runtime?.capital.total ? value / Number(runtime.capital.total) * 100 : 0)}%` }} /></i><strong>{amount(String(value))}</strong></div>)}</div> : <EmptyState title="No portfolio exposure" detail="No underlying, directional, or strategy concentration exists while the paper portfolio is flat." />}</Panel>
      <Panel title="Risk posture" eyebrow="SESSION SURVIVAL" className="risk-posture"><dl className="risk-facts"><div><dt>Drawdown</dt><dd className={drawdown > 0 ? "ats-negative" : undefined}>{(drawdown * 100).toFixed(2)}%</dd></div><div><dt>Session HWM</dt><dd>{amount(runtime?.pnl.session_peak)}</dd></div><div><dt>Loss state</dt><dd>{runtime?.loss_state ?? "UNKNOWN"}</dd></div><div><dt>Correlation</dt><dd>UNKNOWN</dd></div><div><dt>Concentration</dt><dd>{exposures.length <= 1 && exposures.length ? "SINGLE UNDERLYING" : exposures.length ? "DISTRIBUTED" : "NONE"}</dd></div><div><dt>New entries</dt><dd>{runtime ? runtime.session.can_enter && !runtime.paused_new_entries ? "ALLOWED" : "BLOCKED" : "UNKNOWN"}</dd></div></dl></Panel>
      <Panel title="Portfolio Brain decisions" eyebrow="RECORDED EVIDENCE" className="portfolio-decisions">{runtime?.recent_decisions.length ? <div className="decision-list">{runtime.recent_decisions.slice(0, 12).map((decision, index) => { const outcome = String(decision.decision ?? decision.outcome ?? "RECORDED"); return <details key={String(decision.decision_id ?? index)}><summary><StatusBadge state={outcome === "ALLOW" ? "READY" : outcome === "DENY" ? "BLOCKED" : "ACTIVE"}>{outcome}</StatusBadge><span>{String(decision.instrument_id ?? decision.candidate_id ?? `Decision ${index + 1}`)}</span></summary><pre>{JSON.stringify(decision, null, 2)}</pre></details>; })}</div> : <EmptyState title="No recent portfolio decisions" detail="Portfolio Brain has no recorded decisions in the current bounded runtime snapshot." />}</Panel></div>
  </div>;
}
