"""Deterministic valid minimal fixtures for all 18 A02 contracts."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from decimal import Decimal

from ats.contracts import fixture_id
from ats.contracts.domain import (
    AuditEvent,
    AutonomyToken,
    ConfidenceEvidence,
    DecisionPacket,
    ExitIntent,
    FeatureBundle,
    Fill,
    ForecastBundle,
    MarketSnapshot,
    OrderIntent,
    PaperOrder,
    Position,
    RiskDecision,
    RiskFacts,
    StrategyPolicy,
    StrategyPolicyDraft,
    SupervisorAdvisory,
    TradeReview,
)
from ats.contracts.domain.types import (
    AdvisoryOutcome,
    AuditResult,
    AutonomyLevel,
    BaselineResult,
    CooldownRule,
    DataQualityState,
    DataRequirement,
    EligibilityStatus,
    ExitReason,
    ForecastStatus,
    LossState,
    LossStatePolicy,
    MoneyOrPortfolioFraction,
    PaperOrderStatus,
    PaperOrderType,
    PolicyChangeProposal,
    PolicyStatus,
    PortfolioConstraints,
    PositionStatus,
    Predicate,
    PredicateOperator,
    ProbabilityInterval,
    RiskOutcome,
    SessionState,
    Side,
    SizingMode,
    SizingRules,
    StopRule,
    TargetRule,
    TimeExitRule,
    UncertaintyEvidence,
    ValidationIssue,
    ValueKind,
)

NOW = datetime(2026, 1, 2, 9, 15, tzinfo=UTC)
LATER = NOW + timedelta(minutes=5)
HASH = "0" * 64


def uid(name: str):  # type: ignore[no-untyped-def]
    return fixture_id(f"a02/{name}")


def make_contracts() -> dict[str, object]:
    predicate = Predicate(field="close", operator=PredicateOperator.GT, value=100.0)
    loss_policy = LossStatePolicy(
        states=(LossState.NORMAL, LossState.CAUTION, LossState.COOLDOWN, LossState.HALTED)
    )
    proposal = PolicyChangeProposal(
        proposal_id=uid("proposal"),
        summary="Review threshold",
        changes={"confidence_threshold": 0.7},
        executable=False,
    )
    contracts: list[object] = [
        MarketSnapshot(
            snapshot_id=uid("snapshot"),
            instrument_id="RELIANCE",
            exchange="NSE",
            segment="CASH",
            timeframe="5m",
            bar_timestamp=NOW,
            received_at=NOW,
            open=Decimal("100"),
            high=Decimal("110"),
            low=Decimal("95"),
            close=Decimal("105"),
            volume=Decimal("1000"),
            sequence=1,
            quality_state=DataQualityState.GOOD,
            quality_flags=(),
            source="fixture",
            source_version="1",
            session_state=SessionState.OPEN,
            payload_hash=HASH,
        ),
        FeatureBundle(
            feature_bundle_id=uid("features"),
            snapshot_id=uid("snapshot"),
            feature_version="1.0.0",
            features={"momentum": 0.125, "volatility": 1.75},
            quality_flags=(),
            computed_at=NOW,
            input_hash=HASH,
        ),
        ForecastBundle(
            forecast_id=uid("forecast"),
            feature_bundle_id=uid("features"),
            model_id="model",
            model_version="1",
            checkpoint_hash=HASH,
            data_version="1",
            horizon_bars=2,
            event_definition_id="event-definition",
            raw_evidence={"score": 0.5},
            forecast_paths=((100.0, 101.0), (100.0, 99.0)),
            raw_probability=Decimal("0.6"),
            calibrated_probability=Decimal("0.55"),
            calibrator_version="1",
            uncertainty=UncertaintyEvidence(method="quantile", score=0.2),
            baseline_results=(
                BaselineResult(
                    baseline_id="naive",
                    baseline_version="1.0.0",
                    probability=Decimal("0.5"),
                    metrics={"brier": 0.25},
                ),
            ),
            seed=7,
            status=ForecastStatus.READY,
            started_at=NOW,
            completed_at=LATER,
            payload_hash=HASH,
        ),
        ConfidenceEvidence(
            confidence_id=uid("confidence"),
            forecast_id=uid("forecast"),
            event_definition_id="event-definition",
            horizon_bars=2,
            raw_probability=Decimal("0.6"),
            calibrated_probability=Decimal("0.55"),
            calibrator_version="1",
            support_count=100,
            reliability_bin="0.5-0.6",
            brier_score=0.2,
            confidence_interval=ProbabilityInterval(low=Decimal("0.45"), high=Decimal("0.65")),
            regime_label="normal",
            regime_familiarity=0.8,
            data_quality_state=DataQualityState.GOOD,
            ensemble_agreement=0.7,
            baseline_agreement=0.6,
            eligibility_status=EligibilityStatus.ELIGIBLE,
            reason_codes=(),
            computed_at=NOW,
        ),
        StrategyPolicyDraft(
            draft_id=uid("draft"),
            source_instruction_hash=HASH,
            compiler_model_id="compiler",
            compiler_model_version="1",
            requested_autonomy=AutonomyLevel.A2,
            proposed_policy={"timeframe": "5m"},
            ambiguities=(),
            unsafe_requests=(ValidationIssue(code="NONE", message="No unsafe request"),),
            executable=False,
            created_at=NOW,
            payload_hash=HASH,
        ),
        StrategyPolicy(
            policy_id=uid("policy"),
            policy_version=1,
            owner_subject="owner",
            lifecycle_status=PolicyStatus.VALIDATED,
            autonomy_level=AutonomyLevel.A2,
            universe=("RELIANCE",),
            timeframe="5m",
            data_requirements=(
                DataRequirement(requirement_id="bars", description="Five-minute bars"),
            ),
            event_definition_id="event-definition",
            forecast_horizon_bars=2,
            confidence_threshold=Decimal("0.6"),
            minimum_calibration_support=10,
            entry_predicates=(predicate,),
            sizing_rules=SizingRules(
                mode=SizingMode.FIXED_QUANTITY,
                value=Decimal("1"),
            ),
            maximum_loss=MoneyOrPortfolioFraction(
                kind=ValueKind.MONEY,
                value=Decimal("100"),
            ),
            minimum_reward_risk=Decimal("2"),
            stop_rules=(StopRule(rule_id="hard-stop", trigger=predicate, hard_stop=True),),
            target_rules=(TargetRule(rule_id="target", trigger=predicate),),
            trailing_rules=(),
            time_exit=TimeExitRule(maximum_bars=12),
            portfolio_constraints=PortfolioConstraints(
                maximum_open_positions=5,
                maximum_gross_exposure=Decimal("100000"),
                maximum_position_fraction=Decimal("0.2"),
            ),
            daily_loss_limit=Decimal("1000"),
            drawdown_limit=Decimal("0.1"),
            after_loss_state_machine=loss_policy,
            cooldown_rule=CooldownRule(after_consecutive_losses=2, duration_bars=6),
            valid_from=NOW,
            valid_until=NOW + timedelta(days=1),
            compatible_model_versions=("1",),
            compatible_calibrator_versions=("1",),
            created_at=NOW,
            activated_at=None,
            source_instruction_hash=HASH,
            validation_report_hash=HASH,
            payload_hash=HASH,
        ),
        RiskFacts(
            risk_facts_id=uid("risk-facts"),
            snapshot_sequence=1,
            portfolio_version=1,
            policy_id=uid("policy"),
            policy_version=1,
            data_quality_state=DataQualityState.GOOD,
            price_age_ms=10,
            gross_exposure=Decimal("1000"),
            net_exposure=Decimal("1000"),
            open_position_count=1,
            available_cash=Decimal("9000"),
            realized_pnl_today=Decimal("10"),
            unrealized_pnl=Decimal("5"),
            drawdown_fraction=Decimal("0.01"),
            consecutive_losses=0,
            loss_state=LossState.NORMAL,
            liquidity_measure=Decimal("100000"),
            proposed_maximum_loss=Decimal("100"),
            expected_reward=Decimal("200"),
            measured_at=NOW,
            payload_hash=HASH,
        ),
        RiskDecision(
            risk_decision_id=uid("risk-decision"),
            decision=RiskOutcome.ALLOW,
            policy_id=uid("policy"),
            policy_version=1,
            snapshot_sequence=1,
            risk_facts_id=uid("risk-facts"),
            applicable_rule_ids=("max-loss",),
            measured_values={"maximum_loss": Decimal("100")},
            limits={"maximum_loss": Decimal("100")},
            loss_state=LossState.NORMAL,
            reason_codes=(),
            decided_at=NOW,
            payload_hash=HASH,
        ),
        DecisionPacket(
            packet_id=uid("packet"),
            candidate_id=uid("candidate"),
            snapshot_id=uid("snapshot"),
            forecast_id=uid("forecast"),
            confidence_id=uid("confidence"),
            policy_id=uid("policy"),
            policy_version=1,
            risk_decision_id=uid("risk-decision"),
            bounded_evidence={"signal": 0.75},
            created_at=NOW,
            payload_hash=HASH,
        ),
        SupervisorAdvisory(
            advisory_id=uid("advisory"),
            packet_id=uid("packet"),
            recommendation=AdvisoryOutcome.APPROVE,
            evidence_refs=(uid("forecast"),),
            reason_codes=("SUPPORTED",),
            uncertainty_flags=(),
            model_id="supervisor",
            model_version="1",
            latency_ms=5,
            created_at=NOW,
            payload_hash=HASH,
        ),
        AutonomyToken(
            token_id=uid("token"),
            scope="A2_PAPER",
            candidate_id=uid("candidate"),
            policy_id=uid("policy"),
            policy_version=1,
            risk_decision_id=uid("risk-decision"),
            advisory_id=uid("advisory"),
            system_state_version=1,
            issued_at=NOW,
            expires_at=LATER,
            nonce="nonce-1",
            consumed_at=None,
            payload_hash=HASH,
        ),
        OrderIntent(
            intent_id=uid("intent"),
            instrument_id="RELIANCE",
            side=Side.BUY,
            quantity=Decimal("10"),
            order_type=PaperOrderType.MARKET,
            entry_conditions=(predicate,),
            limit_price=None,
            stop_price=None,
            target_price=Decimal("110"),
            maximum_permitted_loss=Decimal("100"),
            expected_reward=Decimal("200"),
            policy_id=uid("policy"),
            policy_version=1,
            forecast_id=uid("forecast"),
            risk_decision_id=uid("risk-decision"),
            supervisor_advisory_id=uid("advisory"),
            autonomy_token_id=uid("token"),
            idempotency_key="intent-1",
            created_at=NOW,
            payload_hash=HASH,
        ),
        PaperOrder(
            paper_order_id=uid("paper-order"),
            intent_id=uid("intent"),
            status=PaperOrderStatus.ACCEPTED,
            instrument_id="RELIANCE",
            side=Side.BUY,
            quantity=Decimal("10"),
            order_type=PaperOrderType.MARKET,
            limit_price=None,
            stop_price=None,
            filled_quantity=Decimal("0"),
            average_fill_price=None,
            rejection_reason=None,
            broker_model_version="1",
            accepted_at=NOW,
            updated_at=NOW,
            idempotency_key="order-1",
            version=1,
        ),
        Fill(
            fill_id=uid("fill"),
            paper_order_id=uid("paper-order"),
            instrument_id="RELIANCE",
            side=Side.BUY,
            quantity=Decimal("10"),
            price=Decimal("100"),
            fees=Decimal("1"),
            taxes=Decimal("0.5"),
            slippage=Decimal("0.1"),
            cost_model_version="1",
            filled_at=NOW,
            idempotency_key="fill-1",
            payload_hash=HASH,
        ),
        Position(
            position_id=uid("position"),
            portfolio_id=uid("portfolio"),
            instrument_id="RELIANCE",
            net_quantity=Decimal("10"),
            average_entry_price=Decimal("100"),
            mark_price=Decimal("101"),
            realized_pnl=Decimal("0"),
            unrealized_pnl=Decimal("10"),
            cash_effect=Decimal("-1000"),
            policy_id=uid("policy"),
            policy_version=1,
            opened_at=NOW,
            updated_at=LATER,
            closed_at=None,
            status=PositionStatus.OPEN,
            version=1,
            last_fill_id=uid("fill"),
            payload_hash=HASH,
        ),
        ExitIntent(
            exit_intent_id=uid("exit"),
            position_id=uid("position"),
            position_version=1,
            reason=ExitReason.TARGET,
            quantity=Decimal("10"),
            order_type=PaperOrderType.MARKET,
            limit_price=None,
            stop_price=None,
            risk_decision_id=uid("risk-decision"),
            autonomy_token_id=uid("token"),
            idempotency_key="exit-1",
            created_at=NOW,
            payload_hash=HASH,
        ),
        TradeReview(
            review_id=uid("review"),
            position_id=uid("position"),
            policy_id=uid("policy"),
            policy_version=1,
            forecast_id=uid("forecast"),
            confidence_id=uid("confidence"),
            outcome_metrics={"return": 0.05},
            attribution={"entry": "signal"},
            lessons=("Keep bounded evidence",),
            policy_change_proposals=(proposal,),
            reviewer_model_id="reviewer",
            reviewer_model_version="1",
            created_at=NOW,
            payload_hash=HASH,
        ),
        AuditEvent(
            audit_event_id=uid("audit"),
            event_id=uid("event"),
            actor_type="SYSTEM",
            actor_id="ats",
            action="RECORD",
            object_type="RiskDecision",
            object_id=str(uid("risk-decision")),
            decision_refs=(uid("risk-decision"),),
            before_hash=None,
            after_hash=HASH,
            result=AuditResult.SUCCESS,
            reason_codes=(),
            occurred_at=NOW,
            trace_id=uid("trace"),
            record_hash=HASH,
        ),
    ]
    return {type(contract).__name__: contract for contract in contracts}
