"use client";

import { useMemo, useState } from "react";
import { useOperatorState } from "../system/OperatorStateProvider";
import { StatusBadge } from "../system/SystemHealthIndicator";
import { formatTimeIST } from "../../lib/formatTime";
import { TruthChart } from "./TruthChart";
import { candlesFromEvents, eventInstrument, explainEvent, presenceFromEvents, type CockpitInstrument } from "./cockpitModel";

const money = (value: string | number | undefined, signed = false) => value === undefined ? "—" : `${signed && Number(value) >= 0 ? "+" : ""}₹${Number(value).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
const valueFrom = (payload: Record<string, unknown>, keys: string[]) => { for (const key of keys) if (payload[key] !== undefined && payload[key] !== null) return String(payload[key]); return null; };

export function OperatorCockpitV2() {
  const { runtime, pipeline, activity, events, sseStatus, loading } = useOperatorState();
  const [instrument, setInstrument] = useState<CockpitInstrument>("NIFTY");
  const [showAgents, setShowAgents] = useState(true);
  const [simple, setSimple] = useState(true);
  const candles = useMemo(() => candlesFromEvents(events, instrument), [events, instrument]);
  const agents = useMemo(() => presenceFromEvents(events), [events]);
  const related = useMemo(() => events.filter((event) => eventInstrument(event) === instrument || eventInstrument(event) === null).slice(-8).reverse(), [events, instrument]);
  const lastPrediction = [...events].reverse().find((event) => eventInstrument(event) === instrument && (event.event_kind.toUpperCase().includes("PREDICT") || event.payload.probability_up !== undefined));
  const pUp = lastPrediction ? valueFrom(lastPrediction.payload, ["probability_up", "p_up", "probability"]) : null;
  const upPercent = pUp === null ? null : Number(pUp) <= 1 ? Number(pUp) * 100 : Number(pUp);
  const totalPnl = Number(runtime?.pnl.realized ?? 0) + Number(runtime?.pnl.unrealized ?? 0);
  return <div className={`operator-cockpit ${simple ? "density-simple" : "density-pro"}`}>
    <div className="cockpit-heading"><div><span>ATS OPERATOR COCKPIT V2</span><h1>Live trading desk</h1></div><div className="cockpit-modes"><button type="button" aria-pressed={simple} onClick={() => setSimple(true)}>Simple</button><button type="button" aria-pressed={!simple} onClick={() => setSimple(false)}>Pro</button><label><input type="checkbox" checked={showAgents} onChange={(event) => setShowAgents(event.target.checked)} /> Agent activity</label></div></div>
    <section className="cockpit-truthbar" aria-label="Capital and safety summary"><StatusBadge state="ACTIVE">PAPER</StatusBadge><div><span>NEW RISK</span><strong>{runtime?.session.can_enter && !runtime.paused_new_entries ? "ALLOWED" : "BLOCKED"}</strong></div><div><span>REDUCTION</span><strong>{runtime?.session.can_reduce ? "ALLOWED" : "BLOCKED"}</strong></div><div><span>CAPITAL</span><strong>{money(runtime?.capital.total)}</strong></div><div><span>AVAILABLE</span><strong>{money(runtime?.capital.available)}</strong></div><div><span>TODAY</span><strong className={totalPnl < 0 ? "ats-negative" : "ats-positive"}>{runtime ? money(totalPnl, true) : "—"}</strong></div><div><span>POSITIONS</span><strong>{runtime?.open_positions.length ?? 0}</strong></div><div><span>QUALIFIED</span><strong>{pipeline?.candidates_qualified ?? 0}</strong></div></section>
    <div className="cockpit-main">
      <aside className="cockpit-watchlist"><header><strong>Watchlist</strong><small>AUTHORITATIVE QUOTES</small></header>{(["NIFTY", "BANKNIFTY"] as const).map((symbol) => { const latest = [...events].reverse().find((event) => eventInstrument(event) === symbol); const ltp = latest ? valueFrom(latest.payload, ["ltp", "last_price", "close", "price"]) : null; return <button type="button" key={symbol} aria-pressed={instrument === symbol} onClick={() => setInstrument(symbol)}><span><strong>{symbol}</strong><small>{latest ? `Updated ${formatTimeIST(latest.occurred_at)}` : "Waiting for market event"}</small></span><b>{ltp ?? "—"}</b><em>{latest ? "CHANGE UNAVAILABLE" : "NO LIVE QUOTE"}</em></button>; })}<div className="agent-dock" data-anchor="INSTRUMENT"><header><strong>Agent presence</strong><small>{showAgents ? "EVENT-BACKED" : "HIDDEN"}</small></header>{showAgents && agents.length ? agents.map((agent) => <details key={agent.role}><summary><i className={agent.status === "ACTIVE" ? "agent-active" : ""} />{agent.role} AGENT <b>{agent.status}</b></summary><p>{agent.activity}</p><small>Authority: advisory only · Evidence: {agent.evidenceRefs.join(", ")}</small></details>) : <p className="agent-idle">{showAgents ? "No typed agent activity received. Agents remain IDLE." : "Cursors hidden; activity remains in the timeline."}</p>}</div></aside>
      <main className="cockpit-center"><TruthChart instrument={instrument} candles={candles} /><section className="prediction-strip"><div><span>PRODUCTION CHAMPION</span><strong>C0</strong><StatusBadge state="READY">PRODUCTION</StatusBadge></div><div><span>P UP</span><strong>{upPercent === null || !Number.isFinite(upPercent) ? "—" : `${upPercent.toFixed(1)}%`}</strong></div><div><span>THRESHOLD</span><strong>55.0%</strong></div><div><span>CURRENT</span><strong>{upPercent !== null && upPercent >= 55 ? "EVIDENCE RECEIVED" : "HOLD"}</strong></div><p>{upPercent === null ? "Prediction unavailable: no authoritative C0 probability event received." : upPercent < 55 ? `No trade. C0 needs ${(55 - upPercent).toFixed(1)} pp more for bullish activation.` : "Activation threshold is met; downstream Portfolio, Risk, and A04 decisions remain authoritative."}</p></section></main>
      <aside className="cockpit-right" data-anchor="OPPORTUNITY"><header><div><small>OPPORTUNITY / ORDER</small><strong>{instrument}</strong></div><StatusBadge state={(pipeline?.candidates_qualified ?? 0) > 0 ? "ACTIVE" : "READY"}>{pipeline?.candidates_qualified ? "QUALIFIED" : "MONITORING"}</StatusBadge></header><div className="authority-rail">{["MARKET", "C0", "THESIS", "PORTFOLIO", "RISK", "A04", "PAPER ORDER"].map((stage, index) => <div key={stage}><i className={index === 0 && runtime?.feed_healthy ? "rail-pass" : ""} /><span>{stage}</span><b>{index === 0 ? runtime?.feed_healthy ? "PASS" : "WAITING" : "NOT REACHED"}</b></div>)}</div><div className="no-opportunity"><strong>{pipeline?.candidates_qualified ? `${pipeline.candidates_qualified} QUALIFIED OPPORTUNITY` : "NO QUALIFIED TRADE RIGHT NOW"}</strong><p>ATS is monitoring real market events. Neutral predictions are summarized instead of flooding the desk.</p><button type="button" className="ats-btn ats-btn-primary" disabled title="Governed manual paper-order endpoint is not attached in this source HEAD">Open PAPER ticket</button><small>Unavailable until the governed operator-order command is attached. PaperBroker is never called from this UI.</small></div></aside>
    </div>
    <div className="cockpit-bottom"><section data-anchor="POSITION"><header><strong>Open positions</strong><small>PAPER · SERVER AUTHORITATIVE</small></header>{runtime?.open_positions.length ? <div className="cockpit-position-list">{runtime.open_positions.map((position) => <article key={position.position_id}><div><strong>{position.instrument_id}</strong><StatusBadge state="ACTIVE">ATS AUTONOMOUS</StatusBadge></div><dl><div><dt>Quantity</dt><dd>{position.quantity}</dd></div><div><dt>Entry</dt><dd>{position.entry_price}</dd></div><div><dt>Current</dt><dd>{position.mark_price ?? "—"}</dd></div><div><dt>P&amp;L</dt><dd>{money(position.unrealized_pnl, true)}</dd></div></dl><p>Position health unavailable until canonical risk evidence is published.</p></article>)}</div> : <div className="cockpit-empty"><strong>NO OPEN POSITIONS</strong><span>ATS is monitoring the market. No trade is required.</span></div>}</section><section className="cockpit-activity"><header><strong>ATS activity</strong><small>{sseStatus.toUpperCase()} · {activity.length} RECORDED</small></header>{related.length ? <ol>{related.map((event) => <li key={event.stream_event_id}><time>{formatTimeIST(event.occurred_at)}</time><div><strong>{event.event_kind.replaceAll("_", " ")}</strong><span>{explainEvent(event)}</span><code>{event.stream_event_id}</code></div></li>)}</ol> : <div className="cockpit-empty"><strong>{loading ? "LOADING ACTIVITY" : "NO MATERIAL EVENTS"}</strong><span>The desk stays calm when ATS has nothing truthful to report.</span></div>}</section></div>
  </div>;
}
