"""Fixed deterministic fixtures for all twenty IBA-C01 contracts."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from decimal import Decimal
from uuid import UUID

from ats.contracts.domain.types import (
    CooldownRule,
    DataQualityState,
    ForecastStatus,
    MoneyOrPortfolioFraction,
    Predicate,
    PredicateOperator,
    ProbabilityInterval,
    SessionState,
    Side,
    ValueKind,
)
from ats.contracts.governance.models import (
    CampaignState,
    GovernanceContext,
    OpportunityCandidate,
    PositionThesis,
    TradingCampaign,
)
from ats.contracts.governance.types import (
    ActionKind,
    CampaignStatus,
    CandidateStatus,
    ConstraintCode,
    ConstraintProvenance,
    ConstraintSource,
    EffectiveConstraintSet,
    PositionRecommendation,
    PositionThesisState,
    RiskDirection,
    StrategyExecutionMode,
    SystemState,
)
from ats.contracts.intelligence.models import (
    AnalogueEvidence,
    AnalystAssessment,
    CalibratedOutcomeDistribution,
    EnsembleForecast,
    ExplanationEvidence,
    FormulaDefinition,
    InstrumentSpec,
    MarketContext,
    MarketThesis,
    PerformanceAttribution,
    PromotionDecision,
    RegimeEvidence,
    StrategyDefinition,
    StrategyExperiment,
    StrategyScorecard,
)
from ats.contracts.intelligence.types import (
    AnalogueMatch,
    AnalogueOutcomeStat,
    AnalystVerdict,
    ApprovalMode,
    AssetClass,
    AttributionCategory,
    AttributionComponent,
    AttributionScope,
    CalibratedOutcome,
    EnsembleMember,
    ExperimentStatus,
    ExperimentType,
    ExplanationAnswerability,
    ExplanationFact,
    FormulaNode,
    FormulaNodeKind,
    FormulaOutputKind,
    FormulaPurpose,
    LeakageScanStatus,
    LiquidityState,
    MarketThesisStatus,
    ParameterValueKind,
    PriceLevel,
    PriceLevelKind,
    PromotionOutcome,
    RegimeDirection,
    RegimeStructure,
    ScorecardValidationStatus,
    Shortability,
    StrategyOrigin,
    StrategyParameter,
    StrategyRef,
    StrategyStatus,
    ThesisStance,
    VersionedRef,
    VolatilityState,
)

HASH = "0" * 64
T0 = datetime(2025, 1, 1, 9, 0, tzinfo=UTC)


def uid(number: int) -> UUID:
    return UUID(int=number)


def make_contracts() -> dict[str, object]:
    predicate = Predicate(field="signal", operator=PredicateOperator.GT, value=1)
    strategy_ref = StrategyRef(strategy_definition_id=uid(40), strategy_definition_version=1)
    versioned_ref = VersionedRef(id=uid(41), version=1)
    money = MoneyOrPortfolioFraction(kind=ValueKind.MONEY, value=Decimal("100"))
    constraints = EffectiveConstraintSet(
        maximum_loss_per_trade=money,
        maximum_campaign_loss=money,
        drawdown_limit=Decimal("0.2"),
        max_trades=10,
        max_concurrent_positions=2,
        capital_budget=Decimal("10000"),
        maximum_budget_per_trade=money,
        minimum_calibrated_probability=Decimal("0.6"),
        minimum_calibration_support=20,
        minimum_expected_edge_r=0.2,
        minimum_reward_risk=Decimal("1.5"),
        allowed_instruments=("ABC",),
        allowed_timeframes=("5m",),
        allowed_strategies=(strategy_ref,),
        strategy_execution_mode=StrategyExecutionMode.CHAMPION_ONLY,
    )
    provenance = tuple(
        ConstraintProvenance(
            constraint_code=code,
            winning_source=ConstraintSource.POLICY,
            source_refs=(uid(50 + index),),
            selected_value=code.value,
        )
        for index, code in enumerate(ConstraintCode)
    )
    feature_node = FormulaNode(
        node_kind=FormulaNodeKind.FEATURE,
        operator=None,
        arguments=(),
        feature_code="close",
        lag_bars=1,
        literal_decimal=None,
        literal_float=None,
        literal_int=None,
        literal_bool=None,
    )
    parameter = StrategyParameter(
        parameter_code="period",
        value_kind=ParameterValueKind.INTEGER,
        integer_value=14,
        decimal_value=None,
        float_value=None,
        boolean_value=None,
        code_value=None,
    )
    instrument = InstrumentSpec(
        schema_version="1.0",
        instrument_spec_id=uid(1),
        instrument_spec_version=1,
        instrument_id="ABC",
        asset_class=AssetClass.CASH_EQUITY,
        venue="NSE",
        symbol="ABC",
        base_asset=None,
        quote_currency="INR",
        settlement_currency="INR",
        tick_size=Decimal("0.05"),
        quantity_step=Decimal("1"),
        minimum_quantity=Decimal("1"),
        contract_multiplier=Decimal("1"),
        timezone="Asia/Calcutta",
        session_calendar_id="NSE",
        trading_hours_profile="REGULAR",
        shortability=Shortability.ALLOWED,
        leverage_allowed=False,
        maximum_leverage=None,
        fee_model_id="fees.v1",
        funding_model_id=None,
        corporate_action_policy_id=None,
        supported_timeframes=("5m",),
        effective_from=T0,
        effective_until=None,
        source="registry",
        source_version="1",
        payload_hash=HASH,
    )
    market = MarketContext(
        schema_version="1.0",
        market_context_id=uid(2),
        instrument_spec_id=uid(1),
        instrument_id="ABC",
        snapshot_id=uid(3),
        feature_bundle_id=uid(4),
        timeframe="5m",
        as_of_time=T0,
        data_cutoff=T0,
        session_state=SessionState.OPEN,
        data_quality_state=DataQualityState.GOOD,
        freshness_ms=0,
        liquidity_state=LiquidityState.NORMAL,
        volatility_state=VolatilityState.NORMAL,
        higher_timeframe_context_refs=(),
        related_market_context_refs=(),
        cost_model_version="1",
        input_hash=HASH,
        payload_hash=HASH,
    )
    regime = RegimeEvidence(
        schema_version="1.0",
        regime_evidence_id=uid(5),
        market_context_id=uid(2),
        instrument_id="ABC",
        timeframe="5m",
        as_of_time=T0,
        data_cutoff=T0,
        detector_id="regime",
        detector_version="1",
        direction=RegimeDirection.UP,
        structure=RegimeStructure.TREND,
        volatility=VolatilityState.NORMAL,
        liquidity=LiquidityState.NORMAL,
        change_score=0.2,
        regime_familiarity=0.8,
        support_window_bars=20,
        reason_codes=("trend",),
        quality_state=DataQualityState.GOOD,
        payload_hash=HASH,
    )
    match = AnalogueMatch(
        analogue_id=uid(6),
        instrument_id="ABC",
        window_start=T0 - timedelta(days=10),
        window_end=T0 - timedelta(days=9),
        similarity_score=0.9,
        raw_distance=0.1,
        regime_similarity=0.8,
        forward_outcome_code="UP",
        forward_return_fraction=0.02,
        maximum_favourable_excursion_fraction=0.03,
        maximum_adverse_excursion_fraction=-0.01,
    )
    analogue = AnalogueEvidence(
        schema_version="1.0",
        analogue_evidence_id=uid(7),
        market_context_id=uid(2),
        instrument_id="ABC",
        timeframe="5m",
        query_window_start=T0 - timedelta(hours=1),
        query_window_end=T0,
        as_of_time=T0,
        data_cutoff=T0,
        retrieval_method="nearest",
        retrieval_version="1",
        corpus_id=uid(8),
        corpus_version="1",
        corpus_cutoff=T0 - timedelta(days=1),
        requested_top_k=1,
        matches=(match,),
        event_definition_id=uid(9),
        forward_horizon_bars=3,
        outcome_summary=(
            AnalogueOutcomeStat(
                outcome_code="UP",
                count=1,
                empirical_probability=Decimal("1"),
                median_forward_return_fraction=0.02,
                median_mfe_fraction=0.03,
                median_mae_fraction=-0.01,
            ),
        ),
        leakage_check_passed=True,
        quality_state=DataQualityState.GOOD,
        payload_hash=HASH,
    )
    ensemble = EnsembleForecast(
        schema_version="1.0",
        ensemble_forecast_id=uid(10),
        market_context_id=uid(2),
        instrument_id="ABC",
        timeframe="5m",
        event_definition_id=uid(9),
        horizon_bars=3,
        as_of_time=T0,
        data_cutoff=T0,
        aggregation_method="weighted",
        aggregation_version="1",
        members=(
            EnsembleMember(
                forecast_id=uid(11),
                model_id="m",
                model_version="1",
                weight=1.0,
                status=ForecastStatus.READY,
            ),
        ),
        raw_outcomes=(),
        disagreement_score=0.0,
        effective_member_count=1,
        baseline_member_ids=(),
        status=ForecastStatus.UNKNOWN,
        payload_hash=HASH,
    )
    distribution = CalibratedOutcomeDistribution(
        schema_version="1.0",
        distribution_id=uid(12),
        ensemble_forecast_id=uid(10),
        market_context_id=uid(2),
        instrument_id="ABC",
        event_definition_id=uid(9),
        horizon_bars=3,
        as_of_time=T0,
        data_cutoff=T0,
        calibrator_id="isotonic",
        calibrator_version="1",
        calibration_window_start=T0 - timedelta(days=30),
        calibration_window_end=T0,
        support_count=100,
        outcomes=(
            CalibratedOutcome(
                outcome_code="UP",
                probability=Decimal("1"),
                interval=ProbabilityInterval(low=Decimal("0.9"), high=Decimal("1")),
            ),
        ),
        brier_score=0.1,
        expected_calibration_error=0.05,
        regime_conditioned=False,
        regime_evidence_id=None,
        expected_return_fraction=0.02,
        expected_volatility_fraction=0.01,
        expected_mfe_fraction=0.03,
        expected_mae_fraction=-0.01,
        tail_loss_probability=Decimal("0.1"),
        quality_state=DataQualityState.GOOD,
        valid_until=T0 + timedelta(hours=1),
        payload_hash=HASH,
    )
    thesis = MarketThesis(
        schema_version="1.0",
        thesis_id=uid(13),
        thesis_version=1,
        instrument_id="ABC",
        market_context_id=uid(2),
        regime_evidence_id=uid(5),
        analogue_evidence_id=uid(7),
        ensemble_forecast_id=uid(10),
        distribution_id=uid(12),
        timeframe="5m",
        as_of_time=T0,
        data_cutoff=T0,
        stance=ThesisStance.BULLISH,
        thesis_strength=0.8,
        support_levels=(
            PriceLevel(kind=PriceLevelKind.SUPPORT, price=Decimal("99"), source_ref=uid(2)),
        ),
        resistance_levels=(),
        opportunity_conditions=(predicate,),
        invalidation_conditions=(predicate,),
        disagreement_score=0.1,
        evidence_refs=(uid(2),),
        data_quality_state=DataQualityState.GOOD,
        expires_at=T0 + timedelta(hours=1),
        status=MarketThesisStatus.ACTIVE,
        supersedes_version=None,
        invalidation_reason_codes=(),
        payload_hash=HASH,
    )
    assessment = AnalystAssessment(
        schema_version="1.0",
        assessment_id=uid(14),
        thesis_id=uid(13),
        thesis_version=1,
        model_id="analyst",
        model_version="1",
        verdict=AnalystVerdict.SUPPORTS,
        quoted_distribution_id=uid(12),
        reason_codes=("supported",),
        uncertainty_flags=(),
        rationale="Evidence supports the thesis.",
        proposed_guidelines=(),
        evidence_refs=(uid(12),),
        created_at=T0,
        payload_hash=HASH,
    )
    strategy = StrategyDefinition(
        schema_version="1.0",
        strategy_definition_id=uid(40),
        strategy_definition_version=1,
        name="Trend",
        strategy_family="trend",
        status=StrategyStatus.VALIDATED,
        feature_formula_refs=(versioned_ref,),
        entry_formula_ref=versioned_ref,
        exit_formula_refs=(),
        compatible_asset_classes=(AssetClass.CASH_EQUITY,),
        compatible_venues=("NSE",),
        compatible_instruments=("ABC",),
        compatible_timeframes=("5m",),
        required_features=("close",),
        required_model_families=(),
        regime_constraints=(),
        parameters=(parameter,),
        origin=StrategyOrigin.HUMAN,
        parent_strategy_ref=None,
        source_instruction_hash=HASH,
        validation_report_hash=HASH,
        created_at=T0,
        payload_hash=HASH,
    )
    formula = FormulaDefinition(
        schema_version="1.0",
        formula_definition_id=uid(41),
        formula_version=1,
        name="Close",
        purpose=FormulaPurpose.FEATURE,
        output_kind=FormulaOutputKind.DECIMAL,
        timeframe="5m",
        lookback_bars=1,
        warmup_bars=0,
        ast=feature_node,
        ast_depth=1,
        node_count=1,
        max_lag_bars=1,
        required_features=("close",),
        parameters=(parameter,),
        source_instruction_hash=HASH,
        origin=StrategyOrigin.HUMAN,
        created_at=T0,
        payload_hash=HASH,
    )
    experiment = StrategyExperiment(
        schema_version="1.0",
        experiment_id=uid(42),
        strategy_definition_id=uid(40),
        strategy_definition_version=1,
        experiment_type=ExperimentType.BACKTEST,
        status=ExperimentStatus.PLANNED,
        instrument_universe=("ABC",),
        timeframe="5m",
        dataset_manifest_id=uid(43),
        dataset_version="1",
        dataset_cutoff=T0,
        train_start=None,
        train_end=None,
        test_start=T0 - timedelta(days=1),
        test_end=None,
        purge_bars=0,
        embargo_bars=0,
        cost_model_version="1",
        parameter_set_hash=HASH,
        seed=1,
        benchmark_strategy_refs=(),
        leakage_scan_status=LeakageScanStatus.UNKNOWN,
        shadow_campaign_id=None,
        started_at=None,
        completed_at=None,
        scorecard_id=None,
        reason_codes=(),
        payload_hash=HASH,
    )
    scorecard = StrategyScorecard(
        schema_version="1.0",
        scorecard_id=uid(44),
        strategy_definition_id=uid(40),
        strategy_definition_version=1,
        experiment_ids=(uid(42),),
        evaluation_start=T0 - timedelta(days=1),
        evaluation_end=T0,
        sample_count=100,
        trade_count=0,
        net_return_fraction=0.0,
        expectancy_r=0.0,
        profit_factor=None,
        win_rate=None,
        average_win_r=None,
        average_loss_r=None,
        maximum_drawdown=Decimal("0"),
        sharpe=None,
        sortino=None,
        tail_loss_metric=0.0,
        turnover=0.0,
        estimated_costs=Decimal("0"),
        stability_score=0.5,
        parameter_sensitivity_score=0.5,
        regime_coverage_score=0.5,
        benchmark_delta=0.0,
        validation_status=ScorecardValidationStatus.INSUFFICIENT_EVIDENCE,
        created_at=T0,
        payload_hash=HASH,
    )
    promotion = PromotionDecision(
        schema_version="1.0",
        promotion_decision_id=uid(45),
        candidate_strategy_ref=strategy_ref,
        incumbent_strategy_ref=None,
        scorecard_ids=(uid(44),),
        decision=PromotionOutcome.DEFER,
        target_status="CHAMPION",
        approval_mode=ApprovalMode.AUTO_A2,
        required_gates_passed=False,
        minimum_evidence_met=False,
        risk_constraints_unchanged=True,
        approved_by=None,
        approved_at=None,
        effective_from=None,
        reason_codes=("evidence",),
        decided_at=T0,
        payload_hash=HASH,
    )
    attribution = PerformanceAttribution(
        schema_version="1.0",
        attribution_id=uid(46),
        scope_type=AttributionScope.TRADE,
        scope_id=uid(47),
        window_start=T0,
        window_end=T0,
        as_of_time=T0,
        data_cutoff=T0,
        method_id="method",
        method_version="1",
        observed_pnl=Decimal("10"),
        components=(
            AttributionComponent(
                category=AttributionCategory.ENTRY_TIMING,
                contribution_money=Decimal("3"),
                contribution_r=0.3,
                confidence_score=0.8,
                evidence_refs=(uid(2),),
            ),
        ),
        unattributed_residual=Decimal("99"),
        counterfactual_refs=(),
        evidence_refs=(uid(2),),
        quality_state=DataQualityState.GOOD,
        created_at=T0,
        payload_hash=HASH,
    )
    explanation = ExplanationEvidence(
        schema_version="1.0",
        explanation_evidence_id=uid(48),
        query_hash=HASH,
        intent="QUESTION",
        scope_refs=(uid(47),),
        as_of_time=T0,
        data_cutoff=T0,
        causal_event_refs=(),
        decision_refs=(),
        market_evidence_refs=(uid(2),),
        performance_attribution_refs=(uid(46),),
        facts=(ExplanationFact(fact_code="pnl", fact_value="10", evidence_refs=(uid(46),)),),
        missing_information=(),
        answerability=ExplanationAnswerability.FULL,
        created_at=T0,
        payload_hash=HASH,
    )
    campaign = TradingCampaign(
        schema_version="1.0",
        campaign_id=uid(20),
        campaign_version=1,
        name="Paper",
        objective="Test",
        scope="A2_PAPER",
        policy_id=uid(21),
        policy_version=1,
        instrument_universe=("ABC",),
        allowed_strategies=(strategy_ref,),
        strategy_execution_mode=StrategyExecutionMode.CHAMPION_ONLY,
        allowed_timeframes=("5m",),
        max_trades=10,
        max_concurrent_positions=2,
        capital_budget=Decimal("10000"),
        maximum_budget_per_trade=money,
        maximum_loss_per_trade=money,
        maximum_campaign_loss=money,
        drawdown_limit=Decimal("0.2"),
        minimum_calibrated_probability=Decimal("0.6"),
        minimum_calibration_support=20,
        minimum_expected_edge_r=0.2,
        minimum_reward_risk=Decimal("1.5"),
        regime_constraints=(),
        model_requirements=(),
        start_at=T0,
        expires_at=T0 + timedelta(days=1),
        cooldown_rule=CooldownRule(after_consecutive_losses=2, duration_bars=3),
        stop_conditions=(predicate,),
        status=CampaignStatus.DRAFT,
        created_by="owner",
        created_at=T0,
        activated_at=None,
        payload_hash=HASH,
    )
    campaign_state = CampaignState(
        schema_version="1.0",
        campaign_state_id=uid(22),
        campaign_id=uid(20),
        campaign_version=1,
        state_version=1,
        status=CampaignStatus.DRAFT,
        trades_started=0,
        trades_completed=0,
        open_positions=0,
        capital_committed=Decimal("0"),
        realized_pnl=Decimal("0"),
        unrealized_pnl=Decimal("0"),
        maximum_drawdown_observed=Decimal("0"),
        consecutive_losses=0,
        last_trade_at=None,
        cooldown_until=None,
        stop_reason_codes=(),
        as_of_time=T0,
        payload_hash=HASH,
    )
    candidate = OpportunityCandidate(
        schema_version="1.0",
        candidate_id=uid(23),
        candidate_version=1,
        instrument_id="ABC",
        market_context_id=uid(2),
        thesis_id=uid(13),
        thesis_version=1,
        distribution_id=uid(12),
        campaign_id=uid(20),
        campaign_version=1,
        strategy_definition_id=uid(40),
        strategy_definition_version=1,
        side=Side.BUY,
        event_definition_id=uid(9),
        horizon_bars=3,
        target_outcome_code="UP",
        calibrated_probability=Decimal("1"),
        expected_net_edge_r=0.5,
        expected_reward_risk=Decimal("2"),
        entry_conditions=(predicate,),
        proposed_stop_price=Decimal("99"),
        proposed_target_price=Decimal("102"),
        evidence_refs=(uid(12),),
        status=CandidateStatus.CREATED,
        risk_decision_id=None,
        advisory_id=None,
        autonomy_token_id=None,
        created_at=T0,
        expires_at=T0 + timedelta(hours=1),
        payload_hash=HASH,
    )
    position = PositionThesis(
        schema_version="1.0",
        position_thesis_id=uid(24),
        position_thesis_version=1,
        position_id=uid(25),
        position_version=1,
        originating_candidate_id=uid(23),
        entry_thesis_id=uid(13),
        entry_thesis_version=1,
        current_thesis_id=uid(13),
        current_thesis_version=1,
        campaign_id=uid(20),
        campaign_version=1,
        as_of_time=T0,
        data_cutoff=T0,
        state=PositionThesisState.HEALTHY,
        current_distribution_id=uid(12),
        original_invalidation_conditions=(predicate,),
        maximum_favourable_excursion_r=1.0,
        maximum_adverse_excursion_r=-0.2,
        recommended_action=PositionRecommendation.HOLD,
        reason_codes=(),
        evidence_refs=(uid(12),),
        expires_at=T0 + timedelta(hours=1),
        payload_hash=HASH,
    )
    governance = GovernanceContext(
        schema_version="1.0",
        governance_context_id=uid(26),
        action_subject_id=uid(23),
        action_kind=ActionKind.OPEN_POSITION,
        risk_direction=RiskDirection.INCREASE,
        candidate_id=uid(23),
        candidate_version=1,
        position_thesis_id=None,
        position_thesis_version=None,
        system_state=SystemState.READY,
        system_state_version=1,
        policy_id=uid(21),
        policy_version=1,
        campaign_id=uid(20),
        campaign_version=1,
        campaign_state_id=uid(22),
        campaign_state_version=1,
        strategy_definition_id=uid(40),
        strategy_definition_version=1,
        portfolio_version=1,
        market_context_id=uid(2),
        risk_facts_id=uid(27),
        data_quality_state=DataQualityState.GOOD,
        data_freshness_ms=0,
        authority_scope="A2_PAPER",
        resolved_constraints=constraints,
        constraint_provenance=provenance,
        source_refs=(uid(2), uid(21)),
        created_at=T0,
        payload_hash=HASH,
    )
    values = (
        instrument,
        market,
        regime,
        analogue,
        ensemble,
        distribution,
        thesis,
        assessment,
        campaign,
        campaign_state,
        candidate,
        position,
        governance,
        strategy,
        formula,
        experiment,
        scorecard,
        promotion,
        attribution,
        explanation,
    )
    return {type(value).__name__: value for value in values}
