"""Market-data feed adapters; credentials are always injected at this edge."""

from .upstox_v3 import (
    ConnectionState,
    FeedConnection,
    FeedMode,
    FeedPayloadDecoder,
    JsonFeedPayloadDecoder,
    NormalizedFeedUpdate,
    ProtobufDecodingSeam,
    ReconciliationSource,
    SubscriptionEntry,
    SubscriptionRegistry,
    UpdateKind,
    UpstoxFeedAuthorization,
    UpstoxFeedConfiguration,
    UpstoxFeedError,
    UpstoxFeedErrorCode,
    UpstoxV3FeedAdapter,
    UpstoxV3FeedAuthorizer,
    UpstoxV3ProtobufDecoder,
    UpstoxV3Transport,
    WireFormat,
)

__all__ = [
    "ConnectionState",
    "FeedConnection",
    "FeedMode",
    "FeedPayloadDecoder",
    "JsonFeedPayloadDecoder",
    "NormalizedFeedUpdate",
    "ProtobufDecodingSeam",
    "ReconciliationSource",
    "SubscriptionEntry",
    "SubscriptionRegistry",
    "UpdateKind",
    "UpstoxFeedAuthorization",
    "UpstoxFeedConfiguration",
    "UpstoxFeedError",
    "UpstoxFeedErrorCode",
    "UpstoxV3FeedAdapter",
    "UpstoxV3FeedAuthorizer",
    "UpstoxV3ProtobufDecoder",
    "UpstoxV3Transport",
    "WireFormat",
]
