"use client";

import { useCallback, useState } from "react";
import { getApiClient } from "../../lib/api";
import { useOperatorState } from "../../components/system/OperatorStateProvider";
import { EmptyState, ErrorState, LoadingState, Panel } from "../../components/system/SurfaceStates";
import { MetricStrip } from "../../components/system/MetricStrip";
import { StatusBadge } from "../../components/system/SystemHealthIndicator";
import { formatTimeIST } from "../../lib/formatTime";

type Advisory = { provider: string; answer: string; latency_ms: number | null };
export default function HarnessPage() {
  const { harness, loading: shellLoading, error, refresh } = useOperatorState(); const [prompt, setPrompt] = useState("Summarize the current market regime and explain why ATS currently has or does not have executable opportunities. Cite only supplied ATS evidence."); const [evidence, setEvidence] = useState(""); const [advisory, setAdvisory] = useState<Advisory | null>(null); const [asking, setAsking] = useState(false);
  const ask = useCallback(async () => { setAsking(true); try { setAdvisory(await getApiClient().harnessAdvisory({ prompt, evidence_summary: evidence, evidence_refs: [] }) as Advisory); await refresh(); } catch (reason) { setAdvisory({ provider: "ERROR", answer: reason instanceof Error ? reason.message : "Harness advisory unavailable", latency_ms: null }); } finally { setAsking(false); } }, [evidence, prompt, refresh]);
  const state = harness?.harness.state; const healthy = state === "HEALTHY";
  return <div className="ats-page harness-page"><div className="ats-page-heading"><div><span className="eyebrow">AGENT OPERATIONS</span><h1>Harness</h1><p>Evidence-backed advisory agents. Deterministic governors retain all trading authority.</p></div><div className="page-provenance"><StatusBadge state={healthy ? "HEALTHY" : state === "STOPPED" ? "OFFLINE" : harness ? "DEGRADED" : "UNKNOWN"}>HARNESS</StatusBadge><span>ADVISORY_ONLY · LIVE MONEY OFF</span></div></div>
    {error && !harness ? <ErrorState detail={error} onRetry={() => void refresh()} /> : null}
    <MetricStrip items={[{ label: "Health", value: state ?? "UNKNOWN" }, { label: "Authority", value: harness?.harness.authority ?? "ADVISORY_ONLY" }, { label: "Model", value: harness?.llm?.primary_model ?? "UNKNOWN" }, { label: "Fallback", value: harness?.llm?.fallback_model ?? "NONE" }, { label: "Sessions", value: harness?.harness.active_sessions ?? 0 }, { label: "Execution", value: harness?.harness.execution_target ?? "PAPER" }]} />
    <Panel title="Advisory agents" eyebrow="STATUS · TRIGGER · LATENCY · EVIDENCE">{shellLoading && !harness ? <LoadingState rows={4} /> : harness?.agents.length ? <div className="agent-card-grid">{harness.agents.map((agent) => <article key={agent.agent_type}><header><strong>{agent.agent_type}</strong><StatusBadge state={agent.status === "ACTIVE" ? "ACTIVE" : agent.status === "IDLE" ? "READY" : agent.status === "OFFLINE" ? "OFFLINE" : "DEGRADED"}>{agent.status}</StatusBadge></header><dl><div><dt>Last trigger</dt><dd>{agent.last_trigger_at ? formatTimeIST(agent.last_trigger_at) : "NONE"}</dd></div><div><dt>Last advisory</dt><dd>{agent.last_trigger_at ? "RECORDED" : "NONE"}</dd></div><div><dt>Latency</dt><dd>{agent.last_latency_ms === null || agent.last_latency_ms === undefined ? "UNKNOWN" : `${agent.last_latency_ms} ms`}</dd></div><div><dt>Model</dt><dd>{agent.model ?? "UNKNOWN"}</dd></div></dl><footer>Evidence is supplied at invocation; agent output cannot authorize execution.</footer></article>)}</div> : <EmptyState title="No agents registered" detail="The Harness is not reporting an active SESSION_MARKET, POSITION, PORTFOLIO_ANALYST, or RESEARCH agent." />}</Panel>
    <div className="harness-lower"><Panel title="Ask Harness" eyebrow="LOCAL EVIDENCE-BACKED ADVISORY" className="harness-ask"><label htmlFor="harness-prompt">Prompt</label><textarea id="harness-prompt" rows={4} value={prompt} onChange={(event) => setPrompt(event.target.value)} /><label htmlFor="harness-evidence">Evidence summary</label><textarea id="harness-evidence" rows={3} value={evidence} onChange={(event) => setEvidence(event.target.value)} placeholder="Optional recorded ATS evidence" /><button type="button" className="ats-btn ats-btn-primary" disabled={asking || !prompt.trim()} onClick={() => void ask()}>{asking ? "Requesting advisory…" : "Ask advisory agent"}</button>{advisory ? <div className={advisory.provider === "ERROR" ? "advisory-answer advisory-error" : "advisory-answer"} role="status"><strong>{advisory.provider} · {advisory.latency_ms ?? "UNKNOWN"} ms · ADVISORY_ONLY</strong><p>{advisory.answer}</p></div> : null}</Panel>
      <Panel title="Safety boundary" eyebrow="NON-NEGOTIABLE" className="harness-safety"><div className="safety-boundary"><div><StatusBadge state="READY">HARNESS AUTHORITY</StatusBadge><strong>{harness?.harness.authority ?? "ADVISORY_ONLY"}</strong></div><div><StatusBadge state="BLOCKED">REAL ORDER AUTHORITY</StatusBadge><strong>NONE</strong></div><div><StatusBadge state="BLOCKED">LIVE MONEY</StatusBadge><strong>{harness?.harness.live_money ?? "DISABLED"}</strong></div><div><StatusBadge state="READY">EXECUTION TARGET</StatusBadge><strong>{harness?.harness.execution_target ?? "PAPER"}</strong></div></div><p>Harness advisories may explain evidence or propose changes. They cannot bypass Portfolio Brain, A04, session, risk, capital, PaperBroker, or live-money prohibitions.</p></Panel></div>
  </div>;
}
